# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20180730_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200, verbose_name='Haqqında')),
                ('tel', models.CharField(blank=True, max_length=14, verbose_name='Telefon Nömrəsi')),
                ('tarix', models.DateField(blank=True, verbose_name='Doğum Tarixi')),
                ('sex', models.CharField(blank=True, choices=[('1', 'Kişi'), ('2', 'Qadın')], max_length=1, verbose_name='Cins')),
                ('photo', models.ImageField(blank=True, default='pp_default.jpeg', upload_to=users.models.upload_to, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillər',
            },
        ),
    ]
