# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Haqqında'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='pp_default.jpeg', null=True, upload_to=users.models.upload_to, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Kişi'), ('2', 'Qadın')], max_length=1, null=True, verbose_name='Cins'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tarix',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarixi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefon Nömrəsi'),
        ),
    ]
