# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180730_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='pp_default.jpg', null=True, upload_to=users.models.upload_to, verbose_name='Avatar'),
        ),
    ]
