# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180712_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Postlar', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Basliq'),
        ),
    ]
