# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='post.Category', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(verbose_name='Məqalə'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlıq'),
        ),
    ]
