# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='deff', max_length=120, unique=True, verbose_name='Slug title'),
            preserve_default=False,
        ),
    ]
