# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20180718_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to=post.models.upload_to, verbose_name='Post img'),
        ),
    ]
