# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 21:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20180720_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor.fields.RichTextField(verbose_name='Məqalə'),
        ),
    ]
