# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Şərh', 'verbose_name_plural': 'Şərhlər'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': 'Postlar', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Şərh'),
        ),
    ]
