# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20180724_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Şərh'),
        ),
    ]
