# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20180724_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1200, verbose_name='Şərh'),
        ),
    ]
