# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='sender',
            new_name='rsender',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='text',
            new_name='rtext',
        ),
    ]
