# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180816_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
