# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_thing_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
